using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Carbonite
{
    /// <summary>
    /// Indicates that an <see cref="IFreezable{TSelf}"/> implementation should be generated by the Carbonite source generator for the target struct or class.
    /// </summary>
    [AttributeUsage(AttributeTargets.Struct | AttributeTargets.Class, Inherited = true, AllowMultiple = false)]
    public class GenerateFreezableAttribute : Attribute
    {
        public GenerateFreezableAttribute()
        {
            // Nothing to do
        }
    }
}
