name: verify-pull-request
on: [pull_request]
jobs:
  # Reference: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net
  dotnet-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v2.1.0
        with:
          # Optional SDK version(s) to use. If not provided, will install global.json version when available. Examples: 2.2.104, 3.1, 3.1.x
          dotnet-version: 6.x
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      # TODO: Uncomment these once we have unit tests
      #- name: Test
      #  run: dotnet test --no-restore --verbosity normal
  native-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup GCC
        uses: aminya/setup-cpp@v1
        with:
          compiler: gcc
          cmake: true
          ninja: true
      - name: CMake
        run: mkdir build && cd build && cmake -G Ninja ../CarboniteExampleNative
      - name: Build
        run: cmake --build . --target all
